SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, ABS(A.SIZE_OF_COLONY-B.MAX_COLONY) AS YEAR_DEV, A.ID AS ID
FROM ECOLI_DATA AS A
JOIN (SELECT MAX(SIZE_OF_COLONY) AS MAX_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
      FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B ON B.YEAR =  YEAR(A.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC