-- 코드를 입력하세요
SELECT CATEGORY, SUM(SUM_SALES) AS TOTAL_SALES
FROM BOOK AS A
JOIN (SELECT book_id,SUM(SALES) AS SUM_SALES, SALES_DATE
                FROM BOOK_SALES 
                WHERE DATE_FORMAT(SALES_DATE, '%m') = 1
                GROUP BY book_id) AS B ON B.BOOK_ID = A.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY

